---
name: build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      with:
        path: debian

    - name: Install dependencies
      run: |
        sudo apt-get --yes install debhelper

    - name: Build
      working-directory: debian
      run: |
        dpkg-buildpackage --no-sign

    - name: Test
      run: |
        sudo apt-get --yes install ./fonts-blobmoji*.deb

    - uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7
      with:
        name: fonts-blobmoji-deb
        path: fonts-blobmoji*.deb
